### ISSUE TITLE
eval returns -nan

### ISSUE THREAD

**Issue by jiggersplat** [duncanmcn/kdepp#1]
If my data (1d doubles) is all the same value, say n, then eval(n) returns -nan. Is that expected?

**Comment by duncanmcn** [comment]
Yes in that case because the variance is 0 then no valid kernel can be created.

I have updated the code to throw if given data of all the same value.

Thanks for your help to find this one

**Comment by duncanmcn** [comment]
https://github.com/duncanmcn/kdepp/commit/c8c7a67683e592f796462583adfc858f2f1942b4
